# Generated by Django 4.0.3 on 2022-03-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
